# Generated by Django 3.2.6 on 2021-08-26 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='image', upload_to='about/')),
            ],
        ),
        migrations.CreateModel(
            name='Alumni',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='name', max_length=100)),
                ('designation', models.CharField(default='designation', max_length=100)),
                ('image', models.ImageField(default='image', upload_to='alumni/')),
                ('social', models.URLField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Blog Title', max_length=100)),
                ('author', models.CharField(default='Blog Author', max_length=20)),
                ('description', models.CharField(default='description', max_length=300)),
                ('published', models.DateField()),
                ('image', models.ImageField(default='image', upload_to='blog/')),
            ],
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='image', upload_to='gallery/')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Project Title', max_length=100)),
                ('description', models.CharField(default='description', max_length=300)),
                ('image', models.ImageField(default='image', upload_to='project/')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='name', max_length=100)),
                ('designation', models.CharField(default='designation', max_length=100)),
                ('image', models.ImageField(default='image', upload_to='team/')),
            ],
        ),
    ]
