# Generated by Django 3.2.6 on 2021-09-10 19:18

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Image Title', max_length=100)),
                ('image', models.ImageField(default='image', upload_to='about/')),
                ('description', models.CharField(default='About Description', max_length=3000)),
            ],
        ),
        migrations.CreateModel(
            name='AlumniCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categories', models.CharField(default='2021-2022', max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Blog Title', max_length=100)),
                ('author', models.CharField(default='Blog Author', max_length=20)),
                ('description', models.CharField(default='description', max_length=300)),
                ('published', models.DateField()),
                ('image', models.ImageField(default='image', upload_to='blog/')),
                ('medium_link', models.CharField(default='#', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Event title', max_length=100)),
                ('location', models.CharField(default='Event location', max_length=100)),
                ('location_url', models.CharField(default='#', max_length=100)),
                ('description', models.TextField(default='description', max_length=1200)),
                ('image', models.ImageField(default='image', upload_to='events/')),
                ('event_day', models.DateField(default=datetime.datetime(2021, 9, 10, 19, 18, 33, 204218, tzinfo=utc))),
                ('event_time_start',
                 models.TimeField(default=datetime.datetime(2021, 9, 10, 19, 18, 33, 204218, tzinfo=utc))),
                ('event_time_end',
                 models.TimeField(default=datetime.datetime(2021, 9, 10, 19, 18, 33, 204218, tzinfo=utc))),
                ('registration_link', models.CharField(default='#', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Image Title', max_length=100)),
                ('image', models.ImageField(default='image', upload_to='gallery/')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Project Title', max_length=100)),
                ('description', models.CharField(default='Project Description', max_length=300)),
                ('image', models.ImageField(default='image', upload_to='project/')),
                ('link', models.CharField(default='#', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='name', max_length=100)),
                ('designation', models.CharField(default='designation', max_length=100)),
                ('image', models.ImageField(default='image', upload_to='team/')),
            ],
        ),
        migrations.CreateModel(
            name='Alumni',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='name', max_length=100)),
                ('designation', models.CharField(default='designation', max_length=100)),
                ('image', models.ImageField(default='image', upload_to='alumni/')),
                ('social', models.URLField(max_length=250)),
                ('duration', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                               to='core.alumnicategory')),
            ],
        ),
    ]
