# Generated by Django 3.2.6 on 2021-09-10 19:18

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_day',
            field=models.DateField(default=datetime.datetime(2021, 9, 10, 19, 18, 47, 853302, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_time_end',
            field=models.TimeField(default=datetime.datetime(2021, 9, 10, 19, 18, 47, 853302, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_time_start',
            field=models.TimeField(default=datetime.datetime(2021, 9, 10, 19, 18, 47, 853302, tzinfo=utc)),
        ),
    ]
