# Generated by Django 2.2.8 on 2021-09-05 16:12

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210905_1932'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialMedia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insta_link', models.CharField(default='#', max_length=100)),
                ('fb_link', models.CharField(default='#', max_length=100)),
                ('twitter_link', models.CharField(default='#', max_length=100)),
                ('linkedin_link', models.CharField(default='#', max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='event',
            name='isopen',
        ),
        migrations.RemoveField(
            model_name='event',
            name='sub_title',
        ),
        migrations.AddField(
            model_name='event',
            name='event_time',
            field=models.TimeField(default=datetime.datetime(2021, 9, 5, 16, 12, 1, 327964, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='event',
            name='location',
            field=models.CharField(default='Event location', max_length=100),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_day',
            field=models.DateField(default=datetime.datetime(2021, 9, 5, 16, 12, 1, 327964, tzinfo=utc)),
        ),
    ]
