# Generated by Django 2.2.8 on 2021-09-05 16:46

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210905_2142'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='description',
            field=models.CharField(default='About Description', max_length=3000),
        ),
        migrations.AddField(
            model_name='alumni',
            name='description',
            field=models.CharField(default='description', max_length=1200),
        ),
        migrations.AddField(
            model_name='project',
            name='link',
            field=models.CharField(default='#', max_length=100),
        ),
        migrations.AddField(
            model_name='socialmedia',
            name='medium_link',
            field=models.CharField(default='#', max_length=100),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_day',
            field=models.DateField(default=datetime.datetime(2021, 9, 5, 16, 46, 49, 856620, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_time',
            field=models.TimeField(default=datetime.datetime(2021, 9, 5, 16, 46, 49, 856620, tzinfo=utc)),
        ),
    ]
