# Generated by Django 3.2.6 on 2021-09-06 18:17

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0005_auto_20210906_2110'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SocialMedia',
        ),
        migrations.AddField(
            model_name='about',
            name='title',
            field=models.CharField(default='Image Title', max_length=100),
        ),
        migrations.AddField(
            model_name='blog',
            name='medium_link',
            field=models.CharField(default='#', max_length=100),
        ),
        migrations.AddField(
            model_name='gallery',
            name='title',
            field=models.CharField(default='Image Title', max_length=100),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_day',
            field=models.DateField(default=datetime.datetime(2021, 9, 6, 18, 17, 45, 490286, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_time',
            field=models.TimeField(default=datetime.datetime(2021, 9, 6, 18, 17, 45, 490286, tzinfo=utc)),
        ),
    ]
